/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_rodsetc {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_rodsetc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_rodsetc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_rodsetc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setQq(float value) {
    CoreJNI.Common_rodsetc_qq_set(swigCPtr, this, value);
  }

  public float getQq() {
    return CoreJNI.Common_rodsetc_qq_get(swigCPtr, this);
  }

  public void setR(float value) {
    CoreJNI.Common_rodsetc_r_set(swigCPtr, this, value);
  }

  public float getR() {
    return CoreJNI.Common_rodsetc_r_get(swigCPtr, this);
  }

  public void setXell(float value) {
    CoreJNI.Common_rodsetc_xell_set(swigCPtr, this, value);
  }

  public float getXell() {
    return CoreJNI.Common_rodsetc_xell_get(swigCPtr, this);
  }

  public void setRl(float value) {
    CoreJNI.Common_rodsetc_rl_set(swigCPtr, this, value);
  }

  public float getRl() {
    return CoreJNI.Common_rodsetc_rl_get(swigCPtr, this);
  }

  public void setDelr(float value) {
    CoreJNI.Common_rodsetc_delr_set(swigCPtr, this, value);
  }

  public float getDelr() {
    return CoreJNI.Common_rodsetc_delr_get(swigCPtr, this);
  }

  public void setDelrcap(float value) {
    CoreJNI.Common_rodsetc_delrcap_set(swigCPtr, this, value);
  }

  public float getDelrcap() {
    return CoreJNI.Common_rodsetc_delrcap_get(swigCPtr, this);
  }

  public void setCont(float value) {
    CoreJNI.Common_rodsetc_cont_set(swigCPtr, this, value);
  }

  public float getCont() {
    return CoreJNI.Common_rodsetc_cont_get(swigCPtr, this);
  }

  public void setVv1(float value) {
    CoreJNI.Common_rodsetc_vv1_set(swigCPtr, this, value);
  }

  public float getVv1() {
    return CoreJNI.Common_rodsetc_vv1_get(swigCPtr, this);
  }

  public void setVv2(float value) {
    CoreJNI.Common_rodsetc_vv2_set(swigCPtr, this, value);
  }

  public float getVv2() {
    return CoreJNI.Common_rodsetc_vv2_get(swigCPtr, this);
  }

  public void setVv3(float value) {
    CoreJNI.Common_rodsetc_vv3_set(swigCPtr, this, value);
  }

  public float getVv3() {
    return CoreJNI.Common_rodsetc_vv3_get(swigCPtr, this);
  }

  public void setVv4(float value) {
    CoreJNI.Common_rodsetc_vv4_set(swigCPtr, this, value);
  }

  public float getVv4() {
    return CoreJNI.Common_rodsetc_vv4_get(swigCPtr, this);
  }

  public void setQr1(float value) {
    CoreJNI.Common_rodsetc_qr1_set(swigCPtr, this, value);
  }

  public float getQr1() {
    return CoreJNI.Common_rodsetc_qr1_get(swigCPtr, this);
  }

  public void setQl1(float value) {
    CoreJNI.Common_rodsetc_ql1_set(swigCPtr, this, value);
  }

  public float getQl1() {
    return CoreJNI.Common_rodsetc_ql1_get(swigCPtr, this);
  }

  public void setV1(float value) {
    CoreJNI.Common_rodsetc_v1_set(swigCPtr, this, value);
  }

  public float getV1() {
    return CoreJNI.Common_rodsetc_v1_get(swigCPtr, this);
  }

  public void setQr2(float value) {
    CoreJNI.Common_rodsetc_qr2_set(swigCPtr, this, value);
  }

  public float getQr2() {
    return CoreJNI.Common_rodsetc_qr2_get(swigCPtr, this);
  }

  public void setQl2(float value) {
    CoreJNI.Common_rodsetc_ql2_set(swigCPtr, this, value);
  }

  public float getQl2() {
    return CoreJNI.Common_rodsetc_ql2_get(swigCPtr, this);
  }

  public void setV2(float value) {
    CoreJNI.Common_rodsetc_v2_set(swigCPtr, this, value);
  }

  public float getV2() {
    return CoreJNI.Common_rodsetc_v2_get(swigCPtr, this);
  }

  public void setVt(float value) {
    CoreJNI.Common_rodsetc_vt_set(swigCPtr, this, value);
  }

  public float getVt() {
    return CoreJNI.Common_rodsetc_vt_get(swigCPtr, this);
  }

  public void setPiby2(float value) {
    CoreJNI.Common_rodsetc_piby2_set(swigCPtr, this, value);
  }

  public float getPiby2() {
    return CoreJNI.Common_rodsetc_piby2_get(swigCPtr, this);
  }

  public void setPi(float value) {
    CoreJNI.Common_rodsetc_pi_set(swigCPtr, this, value);
  }

  public float getPi() {
    return CoreJNI.Common_rodsetc_pi_get(swigCPtr, this);
  }

  public void setDsum(float value) {
    CoreJNI.Common_rodsetc_dsum_set(swigCPtr, this, value);
  }

  public float getDsum() {
    return CoreJNI.Common_rodsetc_dsum_get(swigCPtr, this);
  }

  public void setIf1rod(int value) {
    CoreJNI.Common_rodsetc_if1rod_set(swigCPtr, this, value);
  }

  public int getIf1rod() {
    return CoreJNI.Common_rodsetc_if1rod_get(swigCPtr, this);
  }

  public void setIf1ell(int value) {
    CoreJNI.Common_rodsetc_if1ell_set(swigCPtr, this, value);
  }

  public int getIf1ell() {
    return CoreJNI.Common_rodsetc_if1ell_get(swigCPtr, this);
  }

  public void setIf1esh(int value) {
    CoreJNI.Common_rodsetc_if1esh_set(swigCPtr, this, value);
  }

  public int getIf1esh() {
    return CoreJNI.Common_rodsetc_if1esh_get(swigCPtr, this);
  }

  public void setIf1shr(int value) {
    CoreJNI.Common_rodsetc_if1shr_set(swigCPtr, this, value);
  }

  public int getIf1shr() {
    return CoreJNI.Common_rodsetc_if1shr_get(swigCPtr, this);
  }

  public void setNeedf1(int value) {
    CoreJNI.Common_rodsetc_needf1_set(swigCPtr, this, value);
  }

  public int getNeedf1() {
    return CoreJNI.Common_rodsetc_needf1_get(swigCPtr, this);
  }

  public void setM1(int value) {
    CoreJNI.Common_rodsetc_m1_set(swigCPtr, this, value);
  }

  public int getM1() {
    return CoreJNI.Common_rodsetc_m1_get(swigCPtr, this);
  }

  public void setM2(int value) {
    CoreJNI.Common_rodsetc_m2_set(swigCPtr, this, value);
  }

  public int getM2() {
    return CoreJNI.Common_rodsetc_m2_get(swigCPtr, this);
  }

  public void setM3(int value) {
    CoreJNI.Common_rodsetc_m3_set(swigCPtr, this, value);
  }

  public int getM3() {
    return CoreJNI.Common_rodsetc_m3_get(swigCPtr, this);
  }

  public void setEpsarod(float value) {
    CoreJNI.Common_rodsetc_epsarod_set(swigCPtr, this, value);
  }

  public float getEpsarod() {
    return CoreJNI.Common_rodsetc_epsarod_get(swigCPtr, this);
  }

  public void setEpsrrod(float value) {
    CoreJNI.Common_rodsetc_epsrrod_set(swigCPtr, this, value);
  }

  public float getEpsrrod() {
    return CoreJNI.Common_rodsetc_epsrrod_get(swigCPtr, this);
  }

  public void setEpsaell(float value) {
    CoreJNI.Common_rodsetc_epsaell_set(swigCPtr, this, value);
  }

  public float getEpsaell() {
    return CoreJNI.Common_rodsetc_epsaell_get(swigCPtr, this);
  }

  public void setEpsrell(float value) {
    CoreJNI.Common_rodsetc_epsrell_set(swigCPtr, this, value);
  }

  public float getEpsrell() {
    return CoreJNI.Common_rodsetc_epsrell_get(swigCPtr, this);
  }

  public void setEpsaesh(float value) {
    CoreJNI.Common_rodsetc_epsaesh_set(swigCPtr, this, value);
  }

  public float getEpsaesh() {
    return CoreJNI.Common_rodsetc_epsaesh_get(swigCPtr, this);
  }

  public void setEpsresh(float value) {
    CoreJNI.Common_rodsetc_epsresh_set(swigCPtr, this, value);
  }

  public float getEpsresh() {
    return CoreJNI.Common_rodsetc_epsresh_get(swigCPtr, this);
  }

  public void setEpsashr(float value) {
    CoreJNI.Common_rodsetc_epsashr_set(swigCPtr, this, value);
  }

  public float getEpsashr() {
    return CoreJNI.Common_rodsetc_epsashr_get(swigCPtr, this);
  }

  public void setEpsrshr(float value) {
    CoreJNI.Common_rodsetc_epsrshr_set(swigCPtr, this, value);
  }

  public float getEpsrshr() {
    return CoreJNI.Common_rodsetc_epsrshr_get(swigCPtr, this);
  }

  public void setAbserr(float value) {
    CoreJNI.Common_rodsetc_abserr_set(swigCPtr, this, value);
  }

  public float getAbserr() {
    return CoreJNI.Common_rodsetc_abserr_get(swigCPtr, this);
  }

  public void setAbserr1(float value) {
    CoreJNI.Common_rodsetc_abserr1_set(swigCPtr, this, value);
  }

  public float getAbserr1() {
    return CoreJNI.Common_rodsetc_abserr1_get(swigCPtr, this);
  }

  public void setKount(int value) {
    CoreJNI.Common_rodsetc_kount_set(swigCPtr, this, value);
  }

  public int getKount() {
    return CoreJNI.Common_rodsetc_kount_get(swigCPtr, this);
  }

  public void setKount1(int value) {
    CoreJNI.Common_rodsetc_kount1_set(swigCPtr, this, value);
  }

  public int getKount1() {
    return CoreJNI.Common_rodsetc_kount1_get(swigCPtr, this);
  }

  public void setKount2(int value) {
    CoreJNI.Common_rodsetc_kount2_set(swigCPtr, this, value);
  }

  public int getKount2() {
    return CoreJNI.Common_rodsetc_kount2_get(swigCPtr, this);
  }

  public void setIfail(int value) {
    CoreJNI.Common_rodsetc_ifail_set(swigCPtr, this, value);
  }

  public int getIfail() {
    return CoreJNI.Common_rodsetc_ifail_get(swigCPtr, this);
  }

  public void setPsiq(float value) {
    CoreJNI.Common_rodsetc_psiq_set(swigCPtr, this, value);
  }

  public float getPsiq() {
    return CoreJNI.Common_rodsetc_psiq_get(swigCPtr, this);
  }

  public void setPhi(float value) {
    CoreJNI.Common_rodsetc_phi_set(swigCPtr, this, value);
  }

  public float getPhi() {
    return CoreJNI.Common_rodsetc_phi_get(swigCPtr, this);
  }

  public void setSth(float value) {
    CoreJNI.Common_rodsetc_sth_set(swigCPtr, this, value);
  }

  public float getSth() {
    return CoreJNI.Common_rodsetc_sth_get(swigCPtr, this);
  }

  public void setNpar(int value) {
    CoreJNI.Common_rodsetc_npar_set(swigCPtr, this, value);
  }

  public int getNpar() {
    return CoreJNI.Common_rodsetc_npar_get(swigCPtr, this);
  }

  public void setLtyprod(int value) {
    CoreJNI.Common_rodsetc_ltyprod_set(swigCPtr, this, value);
  }

  public int getLtyprod() {
    return CoreJNI.Common_rodsetc_ltyprod_get(swigCPtr, this);
  }

  public void setTphizer(float value) {
    CoreJNI.Common_rodsetc_tphizer_set(swigCPtr, this, value);
  }

  public float getTphizer() {
    return CoreJNI.Common_rodsetc_tphizer_get(swigCPtr, this);
  }

  public void setC2pz(float value) {
    CoreJNI.Common_rodsetc_c2pz_set(swigCPtr, this, value);
  }

  public float getC2pz() {
    return CoreJNI.Common_rodsetc_c2pz_get(swigCPtr, this);
  }

  public void setTh1(float value) {
    CoreJNI.Common_rodsetc_th1_set(swigCPtr, this, value);
  }

  public float getTh1() {
    return CoreJNI.Common_rodsetc_th1_get(swigCPtr, this);
  }

  public void setTh2(float value) {
    CoreJNI.Common_rodsetc_th2_set(swigCPtr, this, value);
  }

  public float getTh2() {
    return CoreJNI.Common_rodsetc_th2_get(swigCPtr, this);
  }

  public void setPh1(float value) {
    CoreJNI.Common_rodsetc_ph1_set(swigCPtr, this, value);
  }

  public float getPh1() {
    return CoreJNI.Common_rodsetc_ph1_get(swigCPtr, this);
  }

  public void setPh2(float value) {
    CoreJNI.Common_rodsetc_ph2_set(swigCPtr, this, value);
  }

  public float getPh2() {
    return CoreJNI.Common_rodsetc_ph2_get(swigCPtr, this);
  }

  public void setRmspe(float value) {
    CoreJNI.Common_rodsetc_rmspe_set(swigCPtr, this, value);
  }

  public float getRmspe() {
    return CoreJNI.Common_rodsetc_rmspe_get(swigCPtr, this);
  }

  public void setPrevrmspe(float value) {
    CoreJNI.Common_rodsetc_prevrmspe_set(swigCPtr, this, value);
  }

  public float getPrevrmspe() {
    return CoreJNI.Common_rodsetc_prevrmspe_get(swigCPtr, this);
  }

  public void setEpsaspe(float value) {
    CoreJNI.Common_rodsetc_epsaspe_set(swigCPtr, this, value);
  }

  public float getEpsaspe() {
    return CoreJNI.Common_rodsetc_epsaspe_get(swigCPtr, this);
  }

  public void setEpsrspe(float value) {
    CoreJNI.Common_rodsetc_epsrspe_set(swigCPtr, this, value);
  }

  public float getEpsrspe() {
    return CoreJNI.Common_rodsetc_epsrspe_get(swigCPtr, this);
  }

  public void setPrevrn3(float value) {
    CoreJNI.Common_rodsetc_prevrn3_set(swigCPtr, this, value);
  }

  public float getPrevrn3() {
    return CoreJNI.Common_rodsetc_prevrn3_get(swigCPtr, this);
  }

  public void setPrevellmax(float value) {
    CoreJNI.Common_rodsetc_prevellmax_set(swigCPtr, this, value);
  }

  public float getPrevellmax() {
    return CoreJNI.Common_rodsetc_prevellmax_get(swigCPtr, this);
  }

  public void setQl3(float value) {
    CoreJNI.Common_rodsetc_ql3_set(swigCPtr, this, value);
  }

  public float getQl3() {
    return CoreJNI.Common_rodsetc_ql3_get(swigCPtr, this);
  }

  public void setRn3(float value) {
    CoreJNI.Common_rodsetc_rn3_set(swigCPtr, this, value);
  }

  public float getRn3() {
    return CoreJNI.Common_rodsetc_rn3_get(swigCPtr, this);
  }

  public void setEpsakhol(float value) {
    CoreJNI.Common_rodsetc_epsakhol_set(swigCPtr, this, value);
  }

  public float getEpsakhol() {
    return CoreJNI.Common_rodsetc_epsakhol_get(swigCPtr, this);
  }

  public void setEpsrkhol(float value) {
    CoreJNI.Common_rodsetc_epsrkhol_set(swigCPtr, this, value);
  }

  public float getEpsrkhol() {
    return CoreJNI.Common_rodsetc_epsrkhol_get(swigCPtr, this);
  }

  public void setIf1khol(int value) {
    CoreJNI.Common_rodsetc_if1khol_set(swigCPtr, this, value);
  }

  public int getIf1khol() {
    return CoreJNI.Common_rodsetc_if1khol_get(swigCPtr, this);
  }

  public void setWmaxkhol(float value) {
    CoreJNI.Common_rodsetc_wmaxkhol_set(swigCPtr, this, value);
  }

  public float getWmaxkhol() {
    return CoreJNI.Common_rodsetc_wmaxkhol_get(swigCPtr, this);
  }

  public Common_rodsetc() {
    this(CoreJNI.new_Common_rodsetc(), true);
  }

}
