/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_dmat {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_dmat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_dmat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_dmat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIid(int[] value) {
    CoreJNI.Common_dmat_iid_set(swigCPtr, this, value);
  }

  public int[] getIid() {
    return CoreJNI.Common_dmat_iid_get(swigCPtr, this);
  }

  public void setDwd(SWIGTYPE_p_a_96__float value) {
    CoreJNI.Common_dmat_dwd_set(swigCPtr, this, SWIGTYPE_p_a_96__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_96__float getDwd() {
    long cPtr = CoreJNI.Common_dmat_dwd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_96__float(cPtr, false);
  }

  public void setSvw(float[] value) {
    CoreJNI.Common_dmat_svw_set(swigCPtr, this, value);
  }

  public float[] getSvw() {
    return CoreJNI.Common_dmat_svw_get(swigCPtr, this);
  }

  public void setVvv(SWIGTYPE_p_a_96__float value) {
    CoreJNI.Common_dmat_vvv_set(swigCPtr, this, SWIGTYPE_p_a_96__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_96__float getVvv() {
    long cPtr = CoreJNI.Common_dmat_vvv_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_96__float(cPtr, false);
  }

  public void setCov(SWIGTYPE_p_a_96__float value) {
    CoreJNI.Common_dmat_cov_set(swigCPtr, this, SWIGTYPE_p_a_96__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_96__float getCov() {
    long cPtr = CoreJNI.Common_dmat_cov_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_96__float(cPtr, false);
  }

  public Common_dmat() {
    this(CoreJNI.new_Common_dmat(), true);
  }

}
