/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_three {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_three(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_three obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_three(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setJd(int[] value) {
    CoreJNI.Common_three_jd_set(swigCPtr, this, value);
  }

  public int[] getJd() {
    return CoreJNI.Common_three_jd_get(swigCPtr, this);
  }

  public void setJc(int[] value) {
    CoreJNI.Common_three_jc_set(swigCPtr, this, value);
  }

  public int[] getJc() {
    return CoreJNI.Common_three_jc_get(swigCPtr, this);
  }

  public void setJb(int[] value) {
    CoreJNI.Common_three_jb_set(swigCPtr, this, value);
  }

  public int[] getJb() {
    return CoreJNI.Common_three_jb_get(swigCPtr, this);
  }

  public void setJy(int[] value) {
    CoreJNI.Common_three_jy_set(swigCPtr, this, value);
  }

  public int[] getJy() {
    return CoreJNI.Common_three_jy_get(swigCPtr, this);
  }

  public void setJw(int[] value) {
    CoreJNI.Common_three_jw_set(swigCPtr, this, value);
  }

  public int[] getJw() {
    return CoreJNI.Common_three_jw_get(swigCPtr, this);
  }

  public void setJam(int[] value) {
    CoreJNI.Common_three_jam_set(swigCPtr, this, value);
  }

  public int[] getJam() {
    return CoreJNI.Common_three_jam_get(swigCPtr, this);
  }

  public void setJpq(int[] value) {
    CoreJNI.Common_three_jpq_set(swigCPtr, this, value);
  }

  public int[] getJpq() {
    return CoreJNI.Common_three_jpq_get(swigCPtr, this);
  }

  public void setJsq(int[] value) {
    CoreJNI.Common_three_jsq_set(swigCPtr, this, value);
  }

  public int[] getJsq() {
    return CoreJNI.Common_three_jsq_get(swigCPtr, this);
  }

  public void setJbt(int[] value) {
    CoreJNI.Common_three_jbt_set(swigCPtr, this, value);
  }

  public int[] getJbt() {
    return CoreJNI.Common_three_jbt_get(swigCPtr, this);
  }

  public void setJxx(int[] value) {
    CoreJNI.Common_three_jxx_set(swigCPtr, this, value);
  }

  public int[] getJxx() {
    return CoreJNI.Common_three_jxx_get(swigCPtr, this);
  }

  public void setLcom(SWIGTYPE_p_a_80__int value) {
    CoreJNI.Common_three_lcom_set(swigCPtr, this, SWIGTYPE_p_a_80__int.getCPtr(value));
  }

  public SWIGTYPE_p_a_80__int getLcom() {
    long cPtr = CoreJNI.Common_three_lcom_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_80__int(cPtr, false);
  }

  public void setNoref(int value) {
    CoreJNI.Common_three_noref_set(swigCPtr, this, value);
  }

  public int getNoref() {
    return CoreJNI.Common_three_noref_get(swigCPtr, this);
  }

  public void setNowt(int value) {
    CoreJNI.Common_three_nowt_set(swigCPtr, this, value);
  }

  public int getNowt() {
    return CoreJNI.Common_three_nowt_get(swigCPtr, this);
  }

  public void setSse(float value) {
    CoreJNI.Common_three_sse_set(swigCPtr, this, value);
  }

  public float getSse() {
    return CoreJNI.Common_three_sse_get(swigCPtr, this);
  }

  public void setFit(float[] value) {
    CoreJNI.Common_three_fit_set(swigCPtr, this, value);
  }

  public float[] getFit() {
    return CoreJNI.Common_three_fit_get(swigCPtr, this);
  }

  public void setVar(float value) {
    CoreJNI.Common_three_var_set(swigCPtr, this, value);
  }

  public float getVar() {
    return CoreJNI.Common_three_var_get(swigCPtr, this);
  }

  public void setXdwe(float value) {
    CoreJNI.Common_three_xdwe_set(swigCPtr, this, value);
  }

  public float getXdwe() {
    return CoreJNI.Common_three_xdwe_get(swigCPtr, this);
  }

  public void setNpsmear(int value) {
    CoreJNI.Common_three_npsmear_set(swigCPtr, this, value);
  }

  public int getNpsmear() {
    return CoreJNI.Common_three_npsmear_get(swigCPtr, this);
  }

  public Common_three() {
    this(CoreJNI.new_Common_three(), true);
  }

}
