/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_mainc {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_mainc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_mainc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_mainc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMc1(int[] value) {
    CoreJNI.Common_mainc_mc1_set(swigCPtr, this, value);
  }

  public int[] getMc1() {
    return CoreJNI.Common_mainc_mc1_get(swigCPtr, this);
  }

  public void setMc2(int[] value) {
    CoreJNI.Common_mainc_mc2_set(swigCPtr, this, value);
  }

  public int[] getMc2() {
    return CoreJNI.Common_mainc_mc2_get(swigCPtr, this);
  }

  public void setMclen(int[] value) {
    CoreJNI.Common_mainc_mclen_set(swigCPtr, this, value);
  }

  public int[] getMclen() {
    return CoreJNI.Common_mainc_mclen_get(swigCPtr, this);
  }

  public void setMcstr(SWIGTYPE_p_a_20__int value) {
    CoreJNI.Common_mainc_mcstr_set(swigCPtr, this, SWIGTYPE_p_a_20__int.getCPtr(value));
  }

  public SWIGTYPE_p_a_20__int getMcstr() {
    long cPtr = CoreJNI.Common_mainc_mcstr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_20__int(cPtr, false);
  }

  public void setNncom(int value) {
    CoreJNI.Common_mainc_nncom_set(swigCPtr, this, value);
  }

  public int getNncom() {
    return CoreJNI.Common_mainc_nncom_get(swigCPtr, this);
  }

  public void setMcd(int value) {
    CoreJNI.Common_mainc_mcd_set(swigCPtr, this, value);
  }

  public int getMcd() {
    return CoreJNI.Common_mainc_mcd_get(swigCPtr, this);
  }

  public void setIsp(int[] value) {
    CoreJNI.Common_mainc_isp_set(swigCPtr, this, value);
  }

  public int[] getIsp() {
    return CoreJNI.Common_mainc_isp_get(swigCPtr, this);
  }

  public void setMp1(int[] value) {
    CoreJNI.Common_mainc_mp1_set(swigCPtr, this, value);
  }

  public int[] getMp1() {
    return CoreJNI.Common_mainc_mp1_get(swigCPtr, this);
  }

  public void setMp2(int[] value) {
    CoreJNI.Common_mainc_mp2_set(swigCPtr, this, value);
  }

  public int[] getMp2() {
    return CoreJNI.Common_mainc_mp2_get(swigCPtr, this);
  }

  public void setMplen(int[] value) {
    CoreJNI.Common_mainc_mplen_set(swigCPtr, this, value);
  }

  public int[] getMplen() {
    return CoreJNI.Common_mainc_mplen_get(swigCPtr, this);
  }

  public void setMpstr(SWIGTYPE_p_a_20__int value) {
    CoreJNI.Common_mainc_mpstr_set(swigCPtr, this, SWIGTYPE_p_a_20__int.getCPtr(value));
  }

  public SWIGTYPE_p_a_20__int getMpstr() {
    long cPtr = CoreJNI.Common_mainc_mpstr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_20__int(cPtr, false);
  }

  public void setNnpom(int value) {
    CoreJNI.Common_mainc_nnpom_set(swigCPtr, this, value);
  }

  public int getNnpom() {
    return CoreJNI.Common_mainc_nnpom_get(swigCPtr, this);
  }

  public void setMpd(int value) {
    CoreJNI.Common_mainc_mpd_set(swigCPtr, this, value);
  }

  public int getMpd() {
    return CoreJNI.Common_mainc_mpd_get(swigCPtr, this);
  }

  public Common_mainc() {
    this(CoreJNI.new_Common_mainc(), true);
  }

}
