/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_sqhpc {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_sqhpc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_sqhpc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_sqhpc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDcoeff(SWIGTYPE_p_a_4__double value) {
    CoreJNI.Common_sqhpc_dcoeff_set(swigCPtr, this, SWIGTYPE_p_a_4__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_4__double getDcoeff() {
    long cPtr = CoreJNI.Common_sqhpc_dcoeff_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_4__double(cPtr, false);
  }

  public void setCoeff(SWIGTYPE_p_a_6__float value) {
    CoreJNI.Common_sqhpc_coeff_set(swigCPtr, this, SWIGTYPE_p_a_6__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_6__float getCoeff() {
    long cPtr = CoreJNI.Common_sqhpc_coeff_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_6__float(cPtr, false);
  }

  public Common_sqhpc() {
    this(CoreJNI.new_Common_sqhpc(), true);
  }

}
