/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_pref {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_pref(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_pref obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_pref(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFishsrce(String value) {
    CoreJNI.Common_pref_fishsrce_set(swigCPtr, this, value);
  }

  public String getFishsrce() {
    return CoreJNI.Common_pref_fishsrce_get(swigCPtr, this);
  }

  public void setFishplot(String value) {
    CoreJNI.Common_pref_fishplot_set(swigCPtr, this, value);
  }

  public String getFishplot() {
    return CoreJNI.Common_pref_fishplot_get(swigCPtr, this);
  }

  public void setFishlsin(String value) {
    CoreJNI.Common_pref_fishlsin_set(swigCPtr, this, value);
  }

  public String getFishlsin() {
    return CoreJNI.Common_pref_fishlsin_get(swigCPtr, this);
  }

  public void setLfsrc(int value) {
    CoreJNI.Common_pref_lfsrc_set(swigCPtr, this, value);
  }

  public int getLfsrc() {
    return CoreJNI.Common_pref_lfsrc_get(swigCPtr, this);
  }

  public void setLfplt(int value) {
    CoreJNI.Common_pref_lfplt_set(swigCPtr, this, value);
  }

  public int getLfplt() {
    return CoreJNI.Common_pref_lfplt_get(swigCPtr, this);
  }

  public void setLflsp(int value) {
    CoreJNI.Common_pref_lflsp_set(swigCPtr, this, value);
  }

  public int getLflsp() {
    return CoreJNI.Common_pref_lflsp_get(swigCPtr, this);
  }

  public void setSys(String value) {
    CoreJNI.Common_pref_sys_set(swigCPtr, this, value);
  }

  public String getSys() {
    return CoreJNI.Common_pref_sys_get(swigCPtr, this);
  }

  public Common_pref() {
    this(CoreJNI.new_Common_pref(), true);
  }

}
