/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_jfit {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_jfit(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_jfit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_jfit(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInfit(int value) {
    CoreJNI.Common_jfit_infit_set(swigCPtr, this, value);
  }

  public int getInfit() {
    return CoreJNI.Common_jfit_infit_get(swigCPtr, this);
  }

  public void setItim(int value) {
    CoreJNI.Common_jfit_itim_set(swigCPtr, this, value);
  }

  public int getItim() {
    return CoreJNI.Common_jfit_itim_get(swigCPtr, this);
  }

  public Common_jfit() {
    this(CoreJNI.new_Common_jfit(), true);
  }

}
