/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_sqhpb {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_sqhpb(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_sqhpb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_sqhpb(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAssq(double value) {
    CoreJNI.Common_sqhpb_assq_set(swigCPtr, this, value);
  }

  public double getAssq() {
    return CoreJNI.Common_sqhpb_assq_get(swigCPtr, this);
  }

  public void setBssq(double value) {
    CoreJNI.Common_sqhpb_bssq_set(swigCPtr, this, value);
  }

  public double getBssq() {
    return CoreJNI.Common_sqhpb_bssq_get(swigCPtr, this);
  }

  public void setCssq(double value) {
    CoreJNI.Common_sqhpb_cssq_set(swigCPtr, this, value);
  }

  public double getCssq() {
    return CoreJNI.Common_sqhpb_cssq_get(swigCPtr, this);
  }

  public void setFssq(double value) {
    CoreJNI.Common_sqhpb_fssq_set(swigCPtr, this, value);
  }

  public double getFssq() {
    return CoreJNI.Common_sqhpb_fssq_get(swigCPtr, this);
  }

  public void setEta(float value) {
    CoreJNI.Common_sqhpb_eta_set(swigCPtr, this, value);
  }

  public float getEta() {
    return CoreJNI.Common_sqhpb_eta_get(swigCPtr, this);
  }

  public void setGek(float value) {
    CoreJNI.Common_sqhpb_gek_set(swigCPtr, this, value);
  }

  public float getGek() {
    return CoreJNI.Common_sqhpb_gek_get(swigCPtr, this);
  }

  public void setAk(float value) {
    CoreJNI.Common_sqhpb_ak_set(swigCPtr, this, value);
  }

  public float getAk() {
    return CoreJNI.Common_sqhpb_ak_get(swigCPtr, this);
  }

  public void setU(float value) {
    CoreJNI.Common_sqhpb_u_set(swigCPtr, this, value);
  }

  public float getU() {
    return CoreJNI.Common_sqhpb_u_get(swigCPtr, this);
  }

  public void setVv(float value) {
    CoreJNI.Common_sqhpb_vv_set(swigCPtr, this, value);
  }

  public float getVv() {
    return CoreJNI.Common_sqhpb_vv_get(swigCPtr, this);
  }

  public void setGamk(float value) {
    CoreJNI.Common_sqhpb_gamk_set(swigCPtr, this, value);
  }

  public float getGamk() {
    return CoreJNI.Common_sqhpb_gamk_get(swigCPtr, this);
  }

  public void setSeta(float value) {
    CoreJNI.Common_sqhpb_seta_set(swigCPtr, this, value);
  }

  public float getSeta() {
    return CoreJNI.Common_sqhpb_seta_get(swigCPtr, this);
  }

  public void setSgek(float value) {
    CoreJNI.Common_sqhpb_sgek_set(swigCPtr, this, value);
  }

  public float getSgek() {
    return CoreJNI.Common_sqhpb_sgek_get(swigCPtr, this);
  }

  public void setSak(float value) {
    CoreJNI.Common_sqhpb_sak_set(swigCPtr, this, value);
  }

  public float getSak() {
    return CoreJNI.Common_sqhpb_sak_get(swigCPtr, this);
  }

  public void setScal(float value) {
    CoreJNI.Common_sqhpb_scal_set(swigCPtr, this, value);
  }

  public float getScal() {
    return CoreJNI.Common_sqhpb_scal_get(swigCPtr, this);
  }

  public void setG1(float value) {
    CoreJNI.Common_sqhpb_g1_set(swigCPtr, this, value);
  }

  public float getG1() {
    return CoreJNI.Common_sqhpb_g1_get(swigCPtr, this);
  }

  public void setSig(float value) {
    CoreJNI.Common_sqhpb_sig_set(swigCPtr, this, value);
  }

  public float getSig() {
    return CoreJNI.Common_sqhpb_sig_get(swigCPtr, this);
  }

  public Common_sqhpb() {
    this(CoreJNI.new_Common_sqhpb(), true);
  }

}
