/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_ch {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_ch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_ch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_ch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIs(int value) {
    CoreJNI.Common_ch_is_set(swigCPtr, this, value);
  }

  public int getIs() {
    return CoreJNI.Common_ch_is_get(swigCPtr, this);
  }

  public void setId(int value) {
    CoreJNI.Common_ch_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return CoreJNI.Common_ch_id_get(swigCPtr, this);
  }

  public void setIl(int value) {
    CoreJNI.Common_ch_il_set(swigCPtr, this, value);
  }

  public int getIl() {
    return CoreJNI.Common_ch_il_get(swigCPtr, this);
  }

  public void setJs(int value) {
    CoreJNI.Common_ch_js_set(swigCPtr, this, value);
  }

  public int getJs() {
    return CoreJNI.Common_ch_js_get(swigCPtr, this);
  }

  public void setJdf(int value) {
    CoreJNI.Common_ch_jdf_set(swigCPtr, this, value);
  }

  public int getJdf() {
    return CoreJNI.Common_ch_jdf_get(swigCPtr, this);
  }

  public void setJf(int value) {
    CoreJNI.Common_ch_jf_set(swigCPtr, this, value);
  }

  public int getJf() {
    return CoreJNI.Common_ch_jf_get(swigCPtr, this);
  }

  public void setJl(int value) {
    CoreJNI.Common_ch_jl_set(swigCPtr, this, value);
  }

  public int getJl() {
    return CoreJNI.Common_ch_jl_get(swigCPtr, this);
  }

  public void setJp(int value) {
    CoreJNI.Common_ch_jp_set(swigCPtr, this, value);
  }

  public int getJp() {
    return CoreJNI.Common_ch_jp_get(swigCPtr, this);
  }

  public Common_ch() {
    this(CoreJNI.new_Common_ch(), true);
  }

}
