/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_one {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_one(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_one obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_one(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNch(int[] value) {
    CoreJNI.Common_one_nch_set(swigCPtr, this, value);
  }

  public int[] getNch() {
    return CoreJNI.Common_one_nch_get(swigCPtr, this);
  }

  public void setNc1(int[] value) {
    CoreJNI.Common_one_nc1_set(swigCPtr, this, value);
  }

  public int[] getNc1() {
    return CoreJNI.Common_one_nc1_get(swigCPtr, this);
  }

  public void setNc2(int[] value) {
    CoreJNI.Common_one_nc2_set(swigCPtr, this, value);
  }

  public int[] getNc2() {
    return CoreJNI.Common_one_nc2_get(swigCPtr, this);
  }

  public void setNmc(int[] value) {
    CoreJNI.Common_one_nmc_set(swigCPtr, this, value);
  }

  public int[] getNmc() {
    return CoreJNI.Common_one_nmc_get(swigCPtr, this);
  }

  public void setNc3(int[] value) {
    CoreJNI.Common_one_nc3_set(swigCPtr, this, value);
  }

  public int[] getNc3() {
    return CoreJNI.Common_one_nc3_get(swigCPtr, this);
  }

  public void setNc4(int[] value) {
    CoreJNI.Common_one_nc4_set(swigCPtr, this, value);
  }

  public int[] getNc4() {
    return CoreJNI.Common_one_nc4_get(swigCPtr, this);
  }

  public void setIdc(int[] value) {
    CoreJNI.Common_one_idc_set(swigCPtr, this, value);
  }

  public int[] getIdc() {
    return CoreJNI.Common_one_idc_get(swigCPtr, this);
  }

  public void setNsum(int[] value) {
    CoreJNI.Common_one_nsum_set(swigCPtr, this, value);
  }

  public int[] getNsum() {
    return CoreJNI.Common_one_nsum_get(swigCPtr, this);
  }

  public void setIc1(int[] value) {
    CoreJNI.Common_one_ic1_set(swigCPtr, this, value);
  }

  public int[] getIc1() {
    return CoreJNI.Common_one_ic1_get(swigCPtr, this);
  }

  public void setIc2(int[] value) {
    CoreJNI.Common_one_ic2_set(swigCPtr, this, value);
  }

  public int[] getIc2() {
    return CoreJNI.Common_one_ic2_get(swigCPtr, this);
  }

  public void setIc3(int[] value) {
    CoreJNI.Common_one_ic3_set(swigCPtr, this, value);
  }

  public int[] getIc3() {
    return CoreJNI.Common_one_ic3_get(swigCPtr, this);
  }

  public void setLab(SWIGTYPE_p_a_3__int value) {
    CoreJNI.Common_one_lab_set(swigCPtr, this, SWIGTYPE_p_a_3__int.getCPtr(value));
  }

  public SWIGTYPE_p_a_3__int getLab() {
    long cPtr = CoreJNI.Common_one_lab_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_3__int(cPtr, false);
  }

  public void setLab2(SWIGTYPE_p_a_3__a_20__int value) {
    CoreJNI.Common_one_lab2_set(swigCPtr, this, SWIGTYPE_p_a_3__a_20__int.getCPtr(value));
  }

  public SWIGTYPE_p_a_3__a_20__int getLab2() {
    long cPtr = CoreJNI.Common_one_lab2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_3__a_20__int(cPtr, false);
  }

  public void setRspare(SWIGTYPE_p_a_10__float value) {
    CoreJNI.Common_one_rspare_set(swigCPtr, this, SWIGTYPE_p_a_10__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_10__float getRspare() {
    long cPtr = CoreJNI.Common_one_rspare_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_10__float(cPtr, false);
  }

  public void setC(SWIGTYPE_p_a_1024__float value) {
    CoreJNI.Common_one_c_set(swigCPtr, this, SWIGTYPE_p_a_1024__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_1024__float getC() {
    long cPtr = CoreJNI.Common_one_c_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_1024__float(cPtr, false);
  }

  public void setQ(SWIGTYPE_p_a_1024__float value) {
    CoreJNI.Common_one_q_set(swigCPtr, this, SWIGTYPE_p_a_1024__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_1024__float getQ() {
    long cPtr = CoreJNI.Common_one_q_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_1024__float(cPtr, false);
  }

  public void setE(SWIGTYPE_p_a_1024__float value) {
    CoreJNI.Common_one_e_set(swigCPtr, this, SWIGTYPE_p_a_1024__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_1024__float getE() {
    long cPtr = CoreJNI.Common_one_e_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_1024__float(cPtr, false);
  }

  public void setNdim(int value) {
    CoreJNI.Common_one_ndim_set(swigCPtr, this, value);
  }

  public int getNdim() {
    return CoreJNI.Common_one_ndim_get(swigCPtr, this);
  }

  public Common_one() {
    this(CoreJNI.new_Common_one(), true);
  }

}
