/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_tie {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_tie(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_tie obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_tie(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPc(SWIGTYPE_p_a_12__float value) {
    CoreJNI.Common_tie_pc_set(swigCPtr, this, SWIGTYPE_p_a_12__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_12__float getPc() {
    long cPtr = CoreJNI.Common_tie_pc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_12__float(cPtr, false);
  }

  public void setImod(SWIGTYPE_p_a_12__int value) {
    CoreJNI.Common_tie_imod_set(swigCPtr, this, SWIGTYPE_p_a_12__int.getCPtr(value));
  }

  public SWIGTYPE_p_a_12__int getImod() {
    long cPtr = CoreJNI.Common_tie_imod_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_12__int(cPtr, false);
  }

  public void setNcon(int[] value) {
    CoreJNI.Common_tie_ncon_set(swigCPtr, this, value);
  }

  public int[] getNcon() {
    return CoreJNI.Common_tie_ncon_get(swigCPtr, this);
  }

  public void setNuse(int[] value) {
    CoreJNI.Common_tie_nuse_set(swigCPtr, this, value);
  }

  public int[] getNuse() {
    return CoreJNI.Common_tie_nuse_get(swigCPtr, this);
  }

  public void setNtie(int[] value) {
    CoreJNI.Common_tie_ntie_set(swigCPtr, this, value);
  }

  public int[] getNtie() {
    return CoreJNI.Common_tie_ntie_get(swigCPtr, this);
  }

  public Common_tie() {
    this(CoreJNI.new_Common_tie(), true);
  }

}
