/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_gamfun {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_gamfun(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_gamfun obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_gamfun(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDf(float[] value) {
    CoreJNI.Common_gamfun_df_set(swigCPtr, this, value);
  }

  public float[] getDf() {
    return CoreJNI.Common_gamfun_df_get(swigCPtr, this);
  }

  public void setIgamma(int value) {
    CoreJNI.Common_gamfun_igamma_set(swigCPtr, this, value);
  }

  public int getIgamma() {
    return CoreJNI.Common_gamfun_igamma_get(swigCPtr, this);
  }

  public Common_gamfun() {
    this(CoreJNI.new_Common_gamfun(), true);
  }

}
