/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_work {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_work(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_work obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_work(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRjunk(float[] value) {
    CoreJNI.Common_work_rjunk_set(swigCPtr, this, value);
  }

  public float[] getRjunk() {
    return CoreJNI.Common_work_rjunk_get(swigCPtr, this);
  }

  public Common_work() {
    this(CoreJNI.new_Common_work(), true);
  }

}
