/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_model24 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_model24(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_model24 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_model24(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setJjj(int value) {
    CoreJNI.Common_model24_jjj_set(swigCPtr, this, value);
  }

  public int getJjj() {
    return CoreJNI.Common_model24_jjj_get(swigCPtr, this);
  }

  public Common_model24() {
    this(CoreJNI.new_Common_model24(), true);
  }

}
