/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_axtyp {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_axtyp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_axtyp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_axtyp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLabax(SWIGTYPE_p_a_2__int value) {
    CoreJNI.Common_axtyp_labax_set(swigCPtr, this, SWIGTYPE_p_a_2__int.getCPtr(value));
  }

  public SWIGTYPE_p_a_2__int getLabax() {
    long cPtr = CoreJNI.Common_axtyp_labax_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_2__int(cPtr, false);
  }

  public void setIx(int[] value) {
    CoreJNI.Common_axtyp_ix_set(swigCPtr, this, value);
  }

  public int[] getIx() {
    return CoreJNI.Common_axtyp_ix_get(swigCPtr, this);
  }

  public void setIiy(int[] value) {
    CoreJNI.Common_axtyp_iiy_set(swigCPtr, this, value);
  }

  public int[] getIiy() {
    return CoreJNI.Common_axtyp_iiy_get(swigCPtr, this);
  }

  public void setIlg(int[] value) {
    CoreJNI.Common_axtyp_ilg_set(swigCPtr, this, value);
  }

  public int[] getIlg() {
    return CoreJNI.Common_axtyp_ilg_get(swigCPtr, this);
  }

  public void setIlx(int[] value) {
    CoreJNI.Common_axtyp_ilx_set(swigCPtr, this, value);
  }

  public int[] getIlx() {
    return CoreJNI.Common_axtyp_ilx_get(swigCPtr, this);
  }

  public void setIly(int[] value) {
    CoreJNI.Common_axtyp_ily_set(swigCPtr, this, value);
  }

  public int[] getIly() {
    return CoreJNI.Common_axtyp_ily_get(swigCPtr, this);
  }

  public void setIx1(int[] value) {
    CoreJNI.Common_axtyp_ix1_set(swigCPtr, this, value);
  }

  public int[] getIx1() {
    return CoreJNI.Common_axtyp_ix1_get(swigCPtr, this);
  }

  public void setIx2(int[] value) {
    CoreJNI.Common_axtyp_ix2_set(swigCPtr, this, value);
  }

  public int[] getIx2() {
    return CoreJNI.Common_axtyp_ix2_get(swigCPtr, this);
  }

  public void setIlog(int value) {
    CoreJNI.Common_axtyp_ilog_set(swigCPtr, this, value);
  }

  public int getIlog() {
    return CoreJNI.Common_axtyp_ilog_get(swigCPtr, this);
  }

  public void setIgp(int value) {
    CoreJNI.Common_axtyp_igp_set(swigCPtr, this, value);
  }

  public int getIgp() {
    return CoreJNI.Common_axtyp_igp_get(swigCPtr, this);
  }

  public void setIg1(int value) {
    CoreJNI.Common_axtyp_ig1_set(swigCPtr, this, value);
  }

  public int getIg1() {
    return CoreJNI.Common_axtyp_ig1_get(swigCPtr, this);
  }

  public void setIg2(int value) {
    CoreJNI.Common_axtyp_ig2_set(swigCPtr, this, value);
  }

  public int getIg2() {
    return CoreJNI.Common_axtyp_ig2_get(swigCPtr, this);
  }

  public void setPmn(SWIGTYPE_p_a_2__float value) {
    CoreJNI.Common_axtyp_pmn_set(swigCPtr, this, SWIGTYPE_p_a_2__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_2__float getPmn() {
    long cPtr = CoreJNI.Common_axtyp_pmn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_2__float(cPtr, false);
  }

  public void setPmx(SWIGTYPE_p_a_2__float value) {
    CoreJNI.Common_axtyp_pmx_set(swigCPtr, this, SWIGTYPE_p_a_2__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_2__float getPmx() {
    long cPtr = CoreJNI.Common_axtyp_pmx_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_2__float(cPtr, false);
  }

  public void setShift(float[] value) {
    CoreJNI.Common_axtyp_shift_set(swigCPtr, this, value);
  }

  public float[] getShift() {
    return CoreJNI.Common_axtyp_shift_get(swigCPtr, this);
  }

  public void setNset(int[] value) {
    CoreJNI.Common_axtyp_nset_set(swigCPtr, this, value);
  }

  public int[] getNset() {
    return CoreJNI.Common_axtyp_nset_get(swigCPtr, this);
  }

  public void setLltyp(int[] value) {
    CoreJNI.Common_axtyp_lltyp_set(swigCPtr, this, value);
  }

  public int[] getLltyp() {
    return CoreJNI.Common_axtyp_lltyp_get(swigCPtr, this);
  }

  public void setLsym(int[] value) {
    CoreJNI.Common_axtyp_lsym_set(swigCPtr, this, value);
  }

  public int[] getLsym() {
    return CoreJNI.Common_axtyp_lsym_get(swigCPtr, this);
  }

  public void setLtyp2(int[] value) {
    CoreJNI.Common_axtyp_ltyp2_set(swigCPtr, this, value);
  }

  public int[] getLtyp2() {
    return CoreJNI.Common_axtyp_ltyp2_get(swigCPtr, this);
  }

  public void setLsym2(int[] value) {
    CoreJNI.Common_axtyp_lsym2_set(swigCPtr, this, value);
  }

  public int[] getLsym2() {
    return CoreJNI.Common_axtyp_lsym2_get(swigCPtr, this);
  }

  public void setIpf(int[] value) {
    CoreJNI.Common_axtyp_ipf_set(swigCPtr, this, value);
  }

  public int[] getIpf() {
    return CoreJNI.Common_axtyp_ipf_get(swigCPtr, this);
  }

  public void setIpn(int[] value) {
    CoreJNI.Common_axtyp_ipn_set(swigCPtr, this, value);
  }

  public int[] getIpn() {
    return CoreJNI.Common_axtyp_ipn_get(swigCPtr, this);
  }

  public void setIe(int[] value) {
    CoreJNI.Common_axtyp_ie_set(swigCPtr, this, value);
  }

  public int[] getIe() {
    return CoreJNI.Common_axtyp_ie_get(swigCPtr, this);
  }

  public void setKc(int value) {
    CoreJNI.Common_axtyp_kc_set(swigCPtr, this, value);
  }

  public int getKc() {
    return CoreJNI.Common_axtyp_kc_get(swigCPtr, this);
  }

  public void setK(int value) {
    CoreJNI.Common_axtyp_k_set(swigCPtr, this, value);
  }

  public int getK() {
    return CoreJNI.Common_axtyp_k_get(swigCPtr, this);
  }

  public Common_axtyp() {
    this(CoreJNI.new_Common_axtyp(), true);
  }

}
