/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_slfit {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_slfit(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_slfit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_slfit(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSlx1(float[] value) {
    CoreJNI.Common_slfit_slx1_set(swigCPtr, this, value);
  }

  public float[] getSlx1() {
    return CoreJNI.Common_slfit_slx1_get(swigCPtr, this);
  }

  public void setSlx2(float[] value) {
    CoreJNI.Common_slfit_slx2_set(swigCPtr, this, value);
  }

  public float[] getSlx2() {
    return CoreJNI.Common_slfit_slx2_get(swigCPtr, this);
  }

  public void setSly1(float[] value) {
    CoreJNI.Common_slfit_sly1_set(swigCPtr, this, value);
  }

  public float[] getSly1() {
    return CoreJNI.Common_slfit_sly1_get(swigCPtr, this);
  }

  public void setSly2(float[] value) {
    CoreJNI.Common_slfit_sly2_set(swigCPtr, this, value);
  }

  public float[] getSly2() {
    return CoreJNI.Common_slfit_sly2_get(swigCPtr, this);
  }

  public void setVvar(float[] value) {
    CoreJNI.Common_slfit_vvar_set(swigCPtr, this, value);
  }

  public float[] getVvar() {
    return CoreJNI.Common_slfit_vvar_get(swigCPtr, this);
  }

  public void setGrad(float[] value) {
    CoreJNI.Common_slfit_grad_set(swigCPtr, this, value);
  }

  public float[] getGrad() {
    return CoreJNI.Common_slfit_grad_get(swigCPtr, this);
  }

  public void setRint(float[] value) {
    CoreJNI.Common_slfit_rint_set(swigCPtr, this, value);
  }

  public float[] getRint() {
    return CoreJNI.Common_slfit_rint_get(swigCPtr, this);
  }

  public void setGre(float[] value) {
    CoreJNI.Common_slfit_gre_set(swigCPtr, this, value);
  }

  public float[] getGre() {
    return CoreJNI.Common_slfit_gre_get(swigCPtr, this);
  }

  public void setRe(float[] value) {
    CoreJNI.Common_slfit_re_set(swigCPtr, this, value);
  }

  public float[] getRe() {
    return CoreJNI.Common_slfit_re_get(swigCPtr, this);
  }

  public void setRg1(float[] value) {
    CoreJNI.Common_slfit_rg1_set(swigCPtr, this, value);
  }

  public float[] getRg1() {
    return CoreJNI.Common_slfit_rg1_get(swigCPtr, this);
  }

  public void setRg2(float[] value) {
    CoreJNI.Common_slfit_rg2_set(swigCPtr, this, value);
  }

  public float[] getRg2() {
    return CoreJNI.Common_slfit_rg2_get(swigCPtr, this);
  }

  public void setNsl(int[] value) {
    CoreJNI.Common_slfit_nsl_set(swigCPtr, this, value);
  }

  public int[] getNsl() {
    return CoreJNI.Common_slfit_nsl_get(swigCPtr, this);
  }

  public void setNun(int[] value) {
    CoreJNI.Common_slfit_nun_set(swigCPtr, this, value);
  }

  public int[] getNun() {
    return CoreJNI.Common_slfit_nun_get(swigCPtr, this);
  }

  public void setRmid(float value) {
    CoreJNI.Common_slfit_rmid_set(swigCPtr, this, value);
  }

  public float getRmid() {
    return CoreJNI.Common_slfit_rmid_get(swigCPtr, this);
  }

  public void setSlum1(float[] value) {
    CoreJNI.Common_slfit_slum1_set(swigCPtr, this, value);
  }

  public float[] getSlum1() {
    return CoreJNI.Common_slfit_slum1_get(swigCPtr, this);
  }

  public void setSlum2(float[] value) {
    CoreJNI.Common_slfit_slum2_set(swigCPtr, this, value);
  }

  public float[] getSlum2() {
    return CoreJNI.Common_slfit_slum2_get(swigCPtr, this);
  }

  public void setSlum3(float[] value) {
    CoreJNI.Common_slfit_slum3_set(swigCPtr, this, value);
  }

  public float[] getSlum3() {
    return CoreJNI.Common_slfit_slum3_get(swigCPtr, this);
  }

  public void setSlum4(float[] value) {
    CoreJNI.Common_slfit_slum4_set(swigCPtr, this, value);
  }

  public float[] getSlum4() {
    return CoreJNI.Common_slfit_slum4_get(swigCPtr, this);
  }

  public Common_slfit() {
    this(CoreJNI.new_Common_slfit(), true);
  }

}
