/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_quad {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_quad(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_quad obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_quad(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNmeth(int[] value) {
    CoreJNI.Common_quad_nmeth_set(swigCPtr, this, value);
  }

  public int[] getNmeth() {
    return CoreJNI.Common_quad_nmeth_get(swigCPtr, this);
  }

  public void setNiq(int value) {
    CoreJNI.Common_quad_niq_set(swigCPtr, this, value);
  }

  public int getNiq() {
    return CoreJNI.Common_quad_niq_get(swigCPtr, this);
  }

  public void setNiqmax(int value) {
    CoreJNI.Common_quad_niqmax_set(swigCPtr, this, value);
  }

  public int getNiqmax() {
    return CoreJNI.Common_quad_niqmax_get(swigCPtr, this);
  }

  public void setNwtmax(int value) {
    CoreJNI.Common_quad_nwtmax_set(swigCPtr, this, value);
  }

  public int getNwtmax() {
    return CoreJNI.Common_quad_nwtmax_get(swigCPtr, this);
  }

  public void setIq(int[] value) {
    CoreJNI.Common_quad_iq_set(swigCPtr, this, value);
  }

  public int[] getIq() {
    return CoreJNI.Common_quad_iq_get(swigCPtr, this);
  }

  public void setNgpt(int[] value) {
    CoreJNI.Common_quad_ngpt_set(swigCPtr, this, value);
  }

  public int[] getNgpt() {
    return CoreJNI.Common_quad_ngpt_get(swigCPtr, this);
  }

  public void setIb(int[] value) {
    CoreJNI.Common_quad_ib_set(swigCPtr, this, value);
  }

  public int[] getIb() {
    return CoreJNI.Common_quad_ib_get(swigCPtr, this);
  }

  public void setRg(float[] value) {
    CoreJNI.Common_quad_rg_set(swigCPtr, this, value);
  }

  public float[] getRg() {
    return CoreJNI.Common_quad_rg_get(swigCPtr, this);
  }

  public void setWtr(float[] value) {
    CoreJNI.Common_quad_wtr_set(swigCPtr, this, value);
  }

  public float[] getWtr() {
    return CoreJNI.Common_quad_wtr_get(swigCPtr, this);
  }

  public Common_quad() {
    this(CoreJNI.new_Common_quad(), true);
  }

}
