/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_two {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_two(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_two obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_two(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNt(int value) {
    CoreJNI.Common_two_nt_set(swigCPtr, this, value);
  }

  public int getNt() {
    return CoreJNI.Common_two_nt_get(swigCPtr, this);
  }

  public void setNp(int value) {
    CoreJNI.Common_two_np_set(swigCPtr, this, value);
  }

  public int getNp() {
    return CoreJNI.Common_two_np_get(swigCPtr, this);
  }

  public void setNs(int value) {
    CoreJNI.Common_two_ns_set(swigCPtr, this, value);
  }

  public int getNs() {
    return CoreJNI.Common_two_ns_get(swigCPtr, this);
  }

  public void setNc(int value) {
    CoreJNI.Common_two_nc_set(swigCPtr, this, value);
  }

  public int getNc() {
    return CoreJNI.Common_two_nc_get(swigCPtr, this);
  }

  public void setNn(int value) {
    CoreJNI.Common_two_nn_set(swigCPtr, this, value);
  }

  public int getNn() {
    return CoreJNI.Common_two_nn_get(swigCPtr, this);
  }

  public void setNnn(int[] value) {
    CoreJNI.Common_two_nnn_set(swigCPtr, this, value);
  }

  public int[] getNnn() {
    return CoreJNI.Common_two_nnn_get(swigCPtr, this);
  }

  public void setIw(int value) {
    CoreJNI.Common_two_iw_set(swigCPtr, this, value);
  }

  public int getIw() {
    return CoreJNI.Common_two_iw_get(swigCPtr, this);
  }

  public void setIk(int value) {
    CoreJNI.Common_two_ik_set(swigCPtr, this, value);
  }

  public int getIk() {
    return CoreJNI.Common_two_ik_get(swigCPtr, this);
  }

  public void setIp(int value) {
    CoreJNI.Common_two_ip_set(swigCPtr, this, value);
  }

  public int getIp() {
    return CoreJNI.Common_two_ip_get(swigCPtr, this);
  }

  public void setMs(int value) {
    CoreJNI.Common_two_ms_set(swigCPtr, this, value);
  }

  public int getMs() {
    return CoreJNI.Common_two_ms_get(swigCPtr, this);
  }

  public void setIy(int value) {
    CoreJNI.Common_two_iy_set(swigCPtr, this, value);
  }

  public int getIy() {
    return CoreJNI.Common_two_iy_get(swigCPtr, this);
  }

  public void setLs(int[] value) {
    CoreJNI.Common_two_ls_set(swigCPtr, this, value);
  }

  public int[] getLs() {
    return CoreJNI.Common_two_ls_get(swigCPtr, this);
  }

  public void setNpred(int value) {
    CoreJNI.Common_two_npred_set(swigCPtr, this, value);
  }

  public int getNpred() {
    return CoreJNI.Common_two_npred_get(swigCPtr, this);
  }

  public void setNdat(int value) {
    CoreJNI.Common_two_ndat_set(swigCPtr, this, value);
  }

  public int getNdat() {
    return CoreJNI.Common_two_ndat_get(swigCPtr, this);
  }

  public void setNyc(int value) {
    CoreJNI.Common_two_nyc_set(swigCPtr, this, value);
  }

  public int getNyc() {
    return CoreJNI.Common_two_nyc_get(swigCPtr, this);
  }

  public void setNpr(int value) {
    CoreJNI.Common_two_npr_set(swigCPtr, this, value);
  }

  public int getNpr() {
    return CoreJNI.Common_two_npr_get(swigCPtr, this);
  }

  public void setLs2(int[] value) {
    CoreJNI.Common_two_ls2_set(swigCPtr, this, value);
  }

  public int[] getLs2() {
    return CoreJNI.Common_two_ls2_get(swigCPtr, this);
  }

  public void setLm(int[] value) {
    CoreJNI.Common_two_lm_set(swigCPtr, this, value);
  }

  public int[] getLm() {
    return CoreJNI.Common_two_lm_get(swigCPtr, this);
  }

  public void setLtyp(int[] value) {
    CoreJNI.Common_two_ltyp_set(swigCPtr, this, value);
  }

  public int[] getLtyp() {
    return CoreJNI.Common_two_ltyp_get(swigCPtr, this);
  }

  public void setLpar(SWIGTYPE_p_a_3__int value) {
    CoreJNI.Common_two_lpar_set(swigCPtr, this, SWIGTYPE_p_a_3__int.getCPtr(value));
  }

  public SWIGTYPE_p_a_3__int getLpar() {
    long cPtr = CoreJNI.Common_two_lpar_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_3__int(cPtr, false);
  }

  public void setV(float[] value) {
    CoreJNI.Common_two_v_set(swigCPtr, this, value);
  }

  public float[] getV() {
    return CoreJNI.Common_two_v_get(swigCPtr, this);
  }

  public void setEsd(float[] value) {
    CoreJNI.Common_two_esd_set(swigCPtr, this, value);
  }

  public float[] getEsd() {
    return CoreJNI.Common_two_esd_get(swigCPtr, this);
  }

  public void setPs(float[] value) {
    CoreJNI.Common_two_ps_set(swigCPtr, this, value);
  }

  public float[] getPs() {
    return CoreJNI.Common_two_ps_get(swigCPtr, this);
  }

  public void setIdel(int[] value) {
    CoreJNI.Common_two_idel_set(swigCPtr, this, value);
  }

  public int[] getIdel() {
    return CoreJNI.Common_two_idel_get(swigCPtr, this);
  }

  public void setDel(float[] value) {
    CoreJNI.Common_two_del_set(swigCPtr, this, value);
  }

  public float[] getDel() {
    return CoreJNI.Common_two_del_get(swigCPtr, this);
  }

  public void setDv(float[] value) {
    CoreJNI.Common_two_dv_set(swigCPtr, this, value);
  }

  public float[] getDv() {
    return CoreJNI.Common_two_dv_get(swigCPtr, this);
  }

  public void setVolp(float[] value) {
    CoreJNI.Common_two_volp_set(swigCPtr, this, value);
  }

  public float[] getVolp() {
    return CoreJNI.Common_two_volp_get(swigCPtr, this);
  }

  public void setCon(float[] value) {
    CoreJNI.Common_two_con_set(swigCPtr, this, value);
  }

  public float[] getCon() {
    return CoreJNI.Common_two_con_get(swigCPtr, this);
  }

  public Common_two() {
    this(CoreJNI.new_Common_two(), true);
  }

}
