/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Common_char {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Common_char(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Common_char obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoreJNI.delete_Common_char(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIch(int[] value) {
    CoreJNI.Common_char_ich_set(swigCPtr, this, value);
  }

  public int[] getIch() {
    return CoreJNI.Common_char_ich_get(swigCPtr, this);
  }

  public void setNich(int value) {
    CoreJNI.Common_char_nich_set(swigCPtr, this, value);
  }

  public int getNich() {
    return CoreJNI.Common_char_nich_get(swigCPtr, this);
  }

  public Common_char() {
    this(CoreJNI.new_Common_char(), true);
  }

}
