/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public class Core implements CoreConstants {
  public static void setString(String value) {
    CoreJNI.string_set(value);
  }

  public static String getString() {
    return CoreJNI.string_get();
  }

  public static void init() {
    CoreJNI.init();
  }

  public static void acmod(int idx) {
    CoreJNI.acmod(idx);
  }

  public static void datset() {
    CoreJNI.datset();
  }

  public static int setup(int id, String filename) {
    return CoreJNI.setup(id, filename);
  }

  public static int openshare(int channel, String filename) {
    return CoreJNI.openshare(channel, filename);
  }

  public static void closefile(int channel) {
    CoreJNI.closefile(channel);
  }

  public static void pindex() {
    CoreJNI.pindex();
  }

  public static void talk(String command) {
    CoreJNI.talk(command);
  }

  public static void datin(int index, int iset) {
    CoreJNI.datin(index, iset);
  }

  public static void datin3(int iflag, int iset, int iskip) {
    CoreJNI.datin3(iflag, iset, iskip);
  }

  public static void rnilsill(int iset) {
    CoreJNI.rnilsill(iset);
  }

  public static String getLpar(int n) {
    return CoreJNI.getLpar(n);
  }

  public static int lsqout(String filename, int mode) {
    return CoreJNI.lsqout(filename, mode);
  }

  public static int outp(int i1, int j1, int i2, int j2, String filename, int mode) {
    return CoreJNI.outp(i1, j1, i2, j2, filename, mode);
  }

  public static String conop2(int n) {
    return CoreJNI.conop2(n);
  }

  public static float sqscl(int setno) {
    return CoreJNI.sqscl(setno);
  }

  public static void setlabel(int set, String label, int len) {
    CoreJNI.setlabel(set, label, len);
  }

  public static void setlab2(int line, int set, String label, int len) {
    CoreJNI.setlab2(line, set, label, len);
  }

  public static void range(int set, int min, int max) {
    CoreJNI.range(set, min, max);
  }

  public static void setOne_(Common_one value) {
    CoreJNI.one__set(Common_one.getCPtr(value), value);
  }

  public static Common_one getOne_() {
    long cPtr = CoreJNI.one__get();
    return (cPtr == 0) ? null : new Common_one(cPtr, false);
  }

  public static void setTwo_(Common_two value) {
    CoreJNI.two__set(Common_two.getCPtr(value), value);
  }

  public static Common_two getTwo_() {
    long cPtr = CoreJNI.two__get();
    return (cPtr == 0) ? null : new Common_two(cPtr, false);
  }

  public static void setThree_(Common_three value) {
    CoreJNI.three__set(Common_three.getCPtr(value), value);
  }

  public static Common_three getThree_() {
    long cPtr = CoreJNI.three__get();
    return (cPtr == 0) ? null : new Common_three(cPtr, false);
  }

  public static void setTie_(Common_tie value) {
    CoreJNI.tie__set(Common_tie.getCPtr(value), value);
  }

  public static Common_tie getTie_() {
    long cPtr = CoreJNI.tie__get();
    return (cPtr == 0) ? null : new Common_tie(cPtr, false);
  }

  public static void setChar_(Common_char value) {
    CoreJNI.char__set(Common_char.getCPtr(value), value);
  }

  public static Common_char getChar_() {
    long cPtr = CoreJNI.char__get();
    return (cPtr == 0) ? null : new Common_char(cPtr, false);
  }

  public static void setCh_(Common_ch value) {
    CoreJNI.ch__set(Common_ch.getCPtr(value), value);
  }

  public static Common_ch getCh_() {
    long cPtr = CoreJNI.ch__get();
    return (cPtr == 0) ? null : new Common_ch(cPtr, false);
  }

  public static void setJfit_(Common_jfit value) {
    CoreJNI.jfit__set(Common_jfit.getCPtr(value), value);
  }

  public static Common_jfit getJfit_() {
    long cPtr = CoreJNI.jfit__get();
    return (cPtr == 0) ? null : new Common_jfit(cPtr, false);
  }

  public static void setDmat_(Common_dmat value) {
    CoreJNI.dmat__set(Common_dmat.getCPtr(value), value);
  }

  public static Common_dmat getDmat_() {
    long cPtr = CoreJNI.dmat__get();
    return (cPtr == 0) ? null : new Common_dmat(cPtr, false);
  }

  public static void setPoly_(Common_poly value) {
    CoreJNI.poly__set(Common_poly.getCPtr(value), value);
  }

  public static Common_poly getPoly_() {
    long cPtr = CoreJNI.poly__get();
    return (cPtr == 0) ? null : new Common_poly(cPtr, false);
  }

  public static void setMainc_(Common_mainc value) {
    CoreJNI.mainc__set(Common_mainc.getCPtr(value), value);
  }

  public static Common_mainc getMainc_() {
    long cPtr = CoreJNI.mainc__get();
    return (cPtr == 0) ? null : new Common_mainc(cPtr, false);
  }

  public static void setAxtyp_(Common_axtyp value) {
    CoreJNI.axtyp__set(Common_axtyp.getCPtr(value), value);
  }

  public static Common_axtyp getAxtyp_() {
    long cPtr = CoreJNI.axtyp__get();
    return (cPtr == 0) ? null : new Common_axtyp(cPtr, false);
  }

  public static void setSlfit_(Common_slfit value) {
    CoreJNI.slfit__set(Common_slfit.getCPtr(value), value);
  }

  public static Common_slfit getSlfit_() {
    long cPtr = CoreJNI.slfit__get();
    return (cPtr == 0) ? null : new Common_slfit(cPtr, false);
  }

  public static void setBinpar_(Common_binpar value) {
    CoreJNI.binpar__set(Common_binpar.getCPtr(value), value);
  }

  public static Common_binpar getBinpar_() {
    long cPtr = CoreJNI.binpar__get();
    return (cPtr == 0) ? null : new Common_binpar(cPtr, false);
  }

  public static void setGamfun_(Common_gamfun value) {
    CoreJNI.gamfun__set(Common_gamfun.getCPtr(value), value);
  }

  public static Common_gamfun getGamfun_() {
    long cPtr = CoreJNI.gamfun__get();
    return (cPtr == 0) ? null : new Common_gamfun(cPtr, false);
  }

  public static void setRodsetc_(Common_rodsetc value) {
    CoreJNI.rodsetc__set(Common_rodsetc.getCPtr(value), value);
  }

  public static Common_rodsetc getRodsetc_() {
    long cPtr = CoreJNI.rodsetc__get();
    return (cPtr == 0) ? null : new Common_rodsetc(cPtr, false);
  }

  public static void setSqhpb_(Common_sqhpb value) {
    CoreJNI.sqhpb__set(Common_sqhpb.getCPtr(value), value);
  }

  public static Common_sqhpb getSqhpb_() {
    long cPtr = CoreJNI.sqhpb__get();
    return (cPtr == 0) ? null : new Common_sqhpb(cPtr, false);
  }

  public static void setSqhpc_(Common_sqhpc value) {
    CoreJNI.sqhpc__set(Common_sqhpc.getCPtr(value), value);
  }

  public static Common_sqhpc getSqhpc_() {
    long cPtr = CoreJNI.sqhpc__get();
    return (cPtr == 0) ? null : new Common_sqhpc(cPtr, false);
  }

  public static void setModel24_(Common_model24 value) {
    CoreJNI.model24__set(Common_model24.getCPtr(value), value);
  }

  public static Common_model24 getModel24_() {
    long cPtr = CoreJNI.model24__get();
    return (cPtr == 0) ? null : new Common_model24(cPtr, false);
  }

  public static void setQuad_(Common_quad value) {
    CoreJNI.quad__set(Common_quad.getCPtr(value), value);
  }

  public static Common_quad getQuad_() {
    long cPtr = CoreJNI.quad__get();
    return (cPtr == 0) ? null : new Common_quad(cPtr, false);
  }

  public static void setWork_(Common_work value) {
    CoreJNI.work__set(Common_work.getCPtr(value), value);
  }

  public static Common_work getWork_() {
    long cPtr = CoreJNI.work__get();
    return (cPtr == 0) ? null : new Common_work(cPtr, false);
  }

  public static void setPref_(Common_pref value) {
    CoreJNI.pref__set(Common_pref.getCPtr(value), value);
  }

  public static Common_pref getPref_() {
    long cPtr = CoreJNI.pref__get();
    return (cPtr == 0) ? null : new Common_pref(cPtr, false);
  }

  public static SWIGTYPE_p_a_3__int new_lpar() {
    long cPtr = CoreJNI.new_lpar();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_3__int(cPtr, false);
  }

  public static void free_lpar(SWIGTYPE_p_a_3__int x) {
    CoreJNI.free_lpar(SWIGTYPE_p_a_3__int.getCPtr(x));
  }

  public static void lpar_set(SWIGTYPE_p_a_3__int x, int i, int j, int v) {
    CoreJNI.lpar_set(SWIGTYPE_p_a_3__int.getCPtr(x), i, j, v);
  }

  public static int lpar_get(SWIGTYPE_p_a_3__int x, int i, int j) {
    return CoreJNI.lpar_get(SWIGTYPE_p_a_3__int.getCPtr(x), i, j);
  }

  public static SWIGTYPE_p_a_1024__float new_q() {
    long cPtr = CoreJNI.new_q();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_1024__float(cPtr, false);
  }

  public static void free_q(SWIGTYPE_p_a_1024__float x) {
    CoreJNI.free_q(SWIGTYPE_p_a_1024__float.getCPtr(x));
  }

  public static void q_set(SWIGTYPE_p_a_1024__float x, int i, int j, float v) {
    CoreJNI.q_set(SWIGTYPE_p_a_1024__float.getCPtr(x), i, j, v);
  }

  public static float q_get(SWIGTYPE_p_a_1024__float x, int i, int j) {
    return CoreJNI.q_get(SWIGTYPE_p_a_1024__float.getCPtr(x), i, j);
  }

  public static SWIGTYPE_p_a_1024__float new_c() {
    long cPtr = CoreJNI.new_c();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_1024__float(cPtr, false);
  }

  public static void free_c(SWIGTYPE_p_a_1024__float x) {
    CoreJNI.free_c(SWIGTYPE_p_a_1024__float.getCPtr(x));
  }

  public static void c_set(SWIGTYPE_p_a_1024__float x, int i, int j, float v) {
    CoreJNI.c_set(SWIGTYPE_p_a_1024__float.getCPtr(x), i, j, v);
  }

  public static float c_get(SWIGTYPE_p_a_1024__float x, int i, int j) {
    return CoreJNI.c_get(SWIGTYPE_p_a_1024__float.getCPtr(x), i, j);
  }

  public static SWIGTYPE_p_a_1024__float new_e() {
    long cPtr = CoreJNI.new_e();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_1024__float(cPtr, false);
  }

  public static void free_e(SWIGTYPE_p_a_1024__float x) {
    CoreJNI.free_e(SWIGTYPE_p_a_1024__float.getCPtr(x));
  }

  public static void e_set(SWIGTYPE_p_a_1024__float x, int i, int j, float v) {
    CoreJNI.e_set(SWIGTYPE_p_a_1024__float.getCPtr(x), i, j, v);
  }

  public static float e_get(SWIGTYPE_p_a_1024__float x, int i, int j) {
    return CoreJNI.e_get(SWIGTYPE_p_a_1024__float.getCPtr(x), i, j);
  }

}
