/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fish;

public interface CoreConstants {
  public final static int MN = CoreJNI.MN_get();
  public final static int MV = CoreJNI.MV_get();
  public final static int MC = CoreJNI.MC_get();
  public final static int MW = CoreJNI.MW_get();
  public final static int MF = CoreJNI.MF_get();
  public final static int MI = CoreJNI.MI_get();
}
