C***********************************************************************
        SUBROUTINE GETDL
C       THIS IS GETWIR BORROWED FORM DLVA, AS
C       MODIFIED BY R.J.GREENALL TO ACCEPT FORMAT VERSION 4 FILES
C       IN JUNE 1983
C       THIS SUBROUTINE READS SWPC DATA FILE NUMBER RNO FROM
C       DISK.   
C       MODIFIED BY ADDING COMMON, TO RUN WITH LOQ.FOR SUMMER 1984, R.K.H.
C       ON RETURN THE DATA FILE IS CLOSED.
C*************************************************************************
C==== PCPCPC quick hack 4/10/99 to try G77   RKH

C       DECLARATION
        REAL*4 RVEC(1)
        INTEGER*2 RNO,VECLEN,TITLE(256)
        CHARACTER*80 text
      INCLUDE 'FISHDIM.PAR'
      COMMON/ONE/NCH(MW,7),IC(MW,4),
     *LAB(3,MW),LAB2(20,3,MW),RSPARE(10,MW),C(MN,MW),Q(MN,MW),E(MN,MW),NDIM
	COMMON/CH/IS,ID,IL,JS,JD,JF,JL,JP
        COMMON/WORK/INVEC(12,128),FILL(108464)
C       ACTION SEGMENT
    5   WRITE(JS,101)
  101 FORMAT(1X,'ENTER file name ',$)
        READ(IS,40)text
   40 FORMAT(I6)

        OPEN(UNIT=11,FILE=text,ACCESS='DIRECT',ERR=100)
        GO TO 150

100     CONTINUE

        WRITE(JS,15) text
15      FORMAT(1H ,'ATTEMPT TO OPEN FILE ',/,a80,/,' UNSUCCESSFUL')
	GOTO 5

150     CONTINUE
C       OPEN UNIT=1 SUCCESSFUL
C THE FIRST RECORD CONTAINS THE SRS HEADER (DUMMY RECORD AT PRESENT):
        READ(11,REC=1)(TITLE(J),J=1,256)
        WRITE(JS,160)(TITLE(J),J=1,40)
C THE SECOND RECORD CONTAINS THE FILE TITLE:
        READ(11,REC=2)(TITLE(J),J=1,256)
        WRITE(JS,160)(TITLE(J),J=1,40)
160     FORMAT(1H ,80A2)
	WRITE(JS,102)RNO
  102 FORMAT(1X,'STORE RUN',I6,' AS SET NO. ? ',$)
	READ(IS,40)II
	IF(II.LE.0)GOTO 5
C
c      CALL GETLABEL(II)
C
	WRITE(JF,35)II,(TITLE(J),J=1,40),(LAB(J,II),J=1,3)
   35 FORMAT(1X,'SET(',I2,' ) ',40A2,/,5X,3A4,/)

        DO 200 I=3,12
        READ(11,REC=I)(INVEC(I,J),J=1,128)
200     CONTINUE

        CLOSE(UNIT=11)

C NOW CONVERT CONTENTS OF INREC TO REAL FORMAT IN RVEC
        I=-98
        DO 999 IREC=5,10
C==== NORMALLY PULLS IN A 1024 VECTOR, HERE RESTRICT TO 768 
        DO 999 ILMENT=1,128
        IF(I.LT.1)GOTO 800
        C(I,II)=FLOAT(INVEC(IREC,ILMENT))
	Q(I,II)=FLOAT(I)
	E(I,II)=SQRT(ABS(C(I,II)))
800     I=I+1
999     CONTINUE
	NCH(II,1)=600
	NCH(II,2)=1
	NCH(II,3)=132
	NCH(II,4)=1485
	NCH(II,5)=166
	NCH(II,6)=505
	NCH(II,7)=0
        GOTO 5
        END
C**********************************************************************
